name: piotr_brus_cv
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.0+2
  toggle_switch: "^0.1.4"

  cupertino_icons: ^0.1.2
  flutube: ^0.8.3
  youtube_player: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.7



flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/courses/
    - assets/education/


